version: '3'
services:
  express-app1:
    build: ./blog
    ports:
      - "4001:4000" # Change the host port to avoid conflicts
    depends_on:
      - postgres-db

  express-app2:
    build: ./blog
    ports:
      - "4002:4000" # Change the host port to avoid conflicts
    depends_on:
      - postgres-db

  postgres-db:
    build: ./postgres
    environment:
      POSTGRES_DB: dbname1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hessam123

  nginx:
    build: ./nginx
    image: custom-nginx
    ports:
      - "80:80"
    depends_on:
      - express-app1
      - express-app2