# Use the official PostgreSQL image as the base image
FROM postgres:15

# Environment variables for the PostgreSQL database
ENV POSTGRES_DB dbname1
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD hessam123
